Updated to new FXv2 Style fxmanifest.lua files
calumari/webpack-fivem-manifest pull request #4
Opened 2021-09-08 22:13 UTC by roswellgames

2021-09-11 16:42 UTC, calumari requested changes
Hi, thanks for the PR! I haven't been involved in FiveM in a while and have neglected this project. I believe https://github.com/BlueSky-Development/webpack-fx-manifest is an updated fork. I ran your changes and left a couple of comments.

2021-09-11 16:42 UTC, calumari commented on index.js
> +  name 'resource name'
Can you remove the indentation please? It causes the generated manifest to have indentations too.

2021-09-11 16:42 UTC, calumari commented on index.js
> +  shared_scripts { 'config.lua' }
Any chance you could remove shared, client and server scripts please? IIRC, I tried to keep the generated manifest fairly basic and not tied any project's structure.

2021-09-11 20:01 UTC, roswellgames commented
Hopefully the changes have applied and are to your satisfaction :)

2021-09-19 17:42 UTC, calumari commented
LGMT, thanks!

2021-09-19 17:42 UTC, merged